OpenLM code clean up
os-fpga/Raptor_Tools pull request #45
Opened 2024-03-28 19:59 UTC by NadeemYaseen

Don't need to install OpenLM since we are not using pre-compiled lib.

2024-03-29 01:24 UTC, alaindargelas requested changes
Making a large code chunk as a comment is not good practice.
Can you if-def it with some higher level variable instead?

2024-04-01 07:16 UTC, NadeemYaseen commented
Use if condition to enable the compilation of an example and a separate if condition to use pre-compiled libs.

2024-04-01 07:41 UTC, behzadmehmood approved these changes

2024-04-01 08:13 UTC, NadeemYaseen commented
> Making a large code chunk as a comment is not good practice. Can you if-def it with some higher level variable instead?

@alaindargelas  Please review and let me know if any other change is needed.

2024-04-04 22:39 UTC, merged